<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUHpfR6T\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUHpfR6T/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUHpfR6T.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUHpfR6T\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUHpfR6T\App_KernelDevDebugContainer([
    'container.build_hash' => 'UHpfR6T',
    'container.build_id' => 'e26f3da3',
    'container.build_time' => 1616939920,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUHpfR6T');
