<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'getrequest' => [[], ['_is_api' => true, '_controller' => 'App\\Controller\\ApiTestController::getrequest'], [], [['text', '/get']], [], []],
    'postrequest' => [[], ['_is_api' => true, '_controller' => 'App\\Controller\\ApiTestController::postrequest'], [], [['text', '/post']], [], []],
    'putrequest' => [[], ['_is_api' => true, '_controller' => 'App\\Controller\\ApiTestController::putrequest'], [], [['text', '/put']], [], []],
];
